// EIKEN Grade 3 (英検3級) vocabulary list (~600 words)
const wordList: string[] = [
  // Basic vocabulary
  "about", "after", "again", "ago", "air", "all", "also", "always", "animal",
  "another", "any", "apple", "around", "ask", "away", "back", "bad", "bag",
  "ball", "be", "because", "bed", "big", "bird", "black", "blue", "book",
  "both", "box", "boy", "bread", "breakfast", "brother", "brown", "bus", "but",
  "cake", "call", "can", "car", "cat", "catch", "chair", "change", "child",
  "children", "city", "class", "clean", "close", "club", "color", "come",
  "cook", "cool", "corner", "could", "country", "cup", "cut", "dad", "dark",
  "day", "dear", "desk", "different", "dinner", "dog", "door", "down", "draw",
  "dress", "drink", "drive", "each", "ear", "early", "east", "eat", "egg",
  "end", "enjoy", "even", "evening", "every", "example", "eye", "face", "fall",
  "family", "far", "fast", "father", "feel", "find", "fine", "first", "fish",
  "floor", "fly", "food", "free", "friend", "front", "full", "fun", "game",
  "garden", "get", "girl", "give", "glad", "go", "good", "grandfather",
  "grandmother", "green", "group", "grow", "gym", "hair", "hand", "happy",
  "hard", "have", "head", "heart", "heavy", "help", "here", "high", "him",
  "home", "homework", "horse", "hot", "house", "how", "hundred", "hungry",
  "idea", "important", "join", "jump", "just", "keep", "kind", "kitchen",
  "know", "lake", "large", "last", "late", "later", "left", "leg", "letter",
  "light", "like", "listen", "little", "live", "long", "look", "love", "lunch",
  "make", "many", "map", "math", "maybe", "meet", "milk", "minute", "miss",
  "mom", "money", "month", "morning", "most", "mother", "mountain", "move",
  "much", "music", "name", "near", "need", "new", "next", "nice", "night",
  "north", "now", "often", "old", "open", "orange", "other", "our", "out",
  "over", "own", "park", "party", "people", "picture", "place", "plan",
  "plant", "play", "please", "pool", "poor", "popular", "practice", "pretty",
  "problem", "program", "put", "question", "quickly", "quiet", "rain", "read",
  "really", "red", "rest", "rice", "ride", "right", "river", "road", "room",
  "run", "school", "sea", "season", "see", "send", "shop", "short", "show",
  "sing", "sister", "sit", "sky", "sleep", "slow", "small", "smile", "snow",
  "some", "sometimes", "son", "soon", "sorry", "south", "speak", "special",
  "start", "stay", "still", "stop", "store", "story", "street", "strong",
  "study", "summer", "sun", "swim", "table", "take", "talk", "tall", "team",
  "tell", "test", "than", "that", "their", "then", "there", "these", "thing",
  "think", "those", "time", "tired", "today", "together", "tomorrow", "town",
  "train", "tree", "try", "turn", "under", "use", "usually", "very", "video",
  "visit", "wait", "walk", "want", "warm", "wash", "watch", "water", "way",
  "wear", "week", "well", "west", "what", "when", "where", "which", "white",
  "who", "why", "will", "window", "with", "woman", "wonderful", "word", "work",
  "world", "write", "year", "yellow", "young", "your",

  // Intermediate vocabulary
  "ability", "absent", "accident", "act", "action", "add", "address", "advice",
  "afraid", "age", "agree", "ahead", "already", "although", "amazing", "angry",
  "announce", "answer", "apartment", "appear", "area", "arrive", "art",
  "athlete", "attend", "audience", "aunt", "available", "band", "bath",
  "beach", "beautiful", "become", "before", "begin", "believe", "beside",
  "between", "bicycle", "birthday", "borrow", "bother", "bottom", "brave",
  "break", "bright", "bring", "brush", "build", "burger", "busy", "button",
  "camera", "camp", "capital", "care", "careful", "celebrate", "center",
  "century", "certain", "chance", "cheap", "check", "cheese", "chicken",
  "choice", "choose", "church", "circle", "classic", "click", "cloud", "coast",
  "collect", "college", "comfortable", "common", "competition", "complete",
  "concert", "condition", "connect", "contest", "continue", "control",
  "correct", "cover", "crazy", "culture", "customer", "daily", "dance", "date",
  "daughter", "decide", "deep", "deliver", "develop", "dictionary", "die",
  "difficult", "direction", "discover", "discuss", "distance", "dream",
  "during", "earth", "easy", "education", "effort", "either", "electric",
  "elementary", "emergency", "especially", "event", "excite", "excuse",
  "exercise", "expect", "experience", "explain", "extra", "fact", "fail",
  "famous", "fare", "fashion", "favorite", "feet", "festival", "finally",
  "fire", "flag", "flower", "follow", "forget", "forward", "fresh", "fruit",
  "future", "general", "generous", "gentle", "goal", "grade", "grass",
  "great", "guess", "guide", "guitar", "happen", "health", "healthy",
  "helpful", "hero", "hobby", "hold", "holiday", "hope", "hospital", "hotel",
  "hour", "however", "human", "hurry", "imagine", "improve", "include",
  "increase", "independent", "information", "inside", "interest", "introduce",
  "island", "joy", "judge", "language", "laugh", "learn", "leave", "library",
  "life", "line", "local", "lonely", "luck", "machine", "magazine", "main",
  "market", "matter", "meaning", "message", "middle", "mind", "modern",
  "moment", "museum", "nation", "natural", "nature", "news", "noise", "note",
  "notice", "number", "nurse", "object", "ocean", "offer", "once", "only",
  "opinion", "opportunity", "order", "outside", "paint", "paper", "parent",
  "pass", "patient", "pay", "perhaps", "phone", "phrase", "pick", "planet",
  "police", "pond", "post", "power", "present", "price", "princess", "prize",
  "produce", "project", "promise", "protect", "proud", "provide", "public",
  "purpose", "quarter", "quite", "reach", "reason", "receive", "recent",
  "record", "recycle", "reduce", "refuse", "regret", "relax", "remember",
  "repeat", "reply", "report", "request", "require", "research", "respect",
  "result", "return", "review", "reward", "ring", "robot", "round", "rule",
  "safe", "same", "save", "scene", "science", "scientist", "secret", "section",
  "seem", "select", "serious", "share", "sign", "simple", "since", "situation",
  "size", "skill", "soccer", "social", "solve", "something", "sound", "space",
  "speed", "spend", "sport", "station", "step", "stress", "support", "suppose",
  "sure", "surprise", "survive", "talent", "temperature", "tennis", "theater",
  "thousand", "through", "topic", "tour", "tradition", "traffic", "travel",
  "trouble", "trust", "truth", "twice", "typical", "understand", "unique",
  "until", "upset", "vacation", "value", "variety", "vehicle", "village",
  "voice", "volunteer", "vowel", "waste", "weather", "website", "weekend",
  "whether", "wild", "win", "wonder", "wooden", "worried",
];

// Remove duplicates and sort
const uniqueWordList: string[] = [...new Set(wordList)].sort();

export default uniqueWordList;
